#!/bin/bash

#Usage: keystretch <initial hashing factor> <cpu work multiplier> <memory size> <page size> <num threads> +
#        <derived key size> <salt in hex> <password>\n"
time ./keystretch 1 1 2048 16 1 32 deadbeefbaddaddeadbeefbaddad "Don't tell"
