#!/bin/bash

#Usage: keystretch <sha256 rounds> <cpu work multiplier> <memory size> <page size> <num threads> +
#        <derived key size> <salt in hex> <password>\n"
time ./keystretch 4096 1 2048 16 1 8 deadbeefbaddaddeadbeefbaddad "Don't tell"
